// Avtomatik PTPK mekteb.html-dən çıxarılmış məktəb siyahısı
export const SCHOOL_GROUPS = [
  {
    label: 'Gəncə şəhəri',
    schools: [
      'Gəncə şəhər İ.Qayıbov adına 1 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər Ə.Cavad adına 2 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 3 nömrəli tam orta ümumtəhsil məktəb-liseyi',
      'Gəncə şəhər M.Mehdizadə adına 4 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər M.Ə.Sabir adına 5 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər C.Cabbarlı adına 6 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 7 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər M.P.Vaqif adına 8 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 9 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər M.Hadi adına 10 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər N.Gəncəvi adına 11 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər V.Əliyev adına 12 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər H.Əliyev adına 13 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər M.Müşfiq adına 14 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər M.Əzizbəyov adına 15 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər M.Ş.Vazeh adına 16 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 17 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər N.Aydın adına 18 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 19 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər M.A.Abbaszadə adına 20 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 21 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 22 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 23 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 24 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 25 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 26 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər İ.Məmmədov adına 27 nömrəli tam orta ümumtəhsil məktəb-liseyi',
      'Gəncə şəhər 28 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 29 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 30 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 31 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 32 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 33 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 34 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 35 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 36 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 37 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 38 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 39 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 40 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 41 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 42 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər 43 nömrəli tam orta ümumtəhsil məktəbi',
      'Gəncə şəhər İnteqrasiya təlimli İnternat Tipli Gimnaziya',
      'Gəncə şəhər 45 nömrəli xüsusi məktəbi',
    ],
  },
  {
    label: 'Göygöl rayonu',
    schools: [
      'Göygöl şəhər 1 nömrəli tam orta ümumtəhsil məktəbi',
      'Göygöl şəhər 2 nömrəli tam orta ümumtəhsil məktəb-liseyi',
      'Xaqani kənd tam orta ümumtəhsil məktəbi',
      'Toğanalı kənd tam orta ümumtəhsil məktəbi',
      'Üçtəpə kənd tam orta ümumtəhsil məktəbi',
      'Xanalılar kənd tam orta ümumtəhsil məktəbi',
      'Firuzabad kənd tam orta ümumtəhsil məktəbi',
      'Hacıməlik kənd tam orta ümumtəhsil məktəbi',
      'Aşıqlı kənd tam orta ümumtəhsil məktəbi',
      'Quşqara kənd tam orta ümumtəhsil məktəbi',
      'Balçılı kənd tam orta ümumtəhsil məktəbi',
      'Almalı kənd tam orta ümumtəhsil məktəbi',
      'Çaykənd kənd tam orta ümumtəhsil məktəbi',
      'Çaylı kənd tam orta ümumtəhsil məktəbi',
      'Dozular kənd tam orta ümumtəhsil məktəbi',
      'Gəncə kənd tam orta ümumtəhsil məktəbi',
      'Göykənd kənd ümumi orta məktəbi',
      'Qızılca kənd tam orta ümumtəhsil məktəbi',
      'Köşkü kənd tam orta ümumtəhsil məktəbi',
      'Mollacəlilli kənd tam orta ümumtəhsil məktəbi',
      'Nadel kənd tam orta ümumtəhsil məktəbi',
      'Pənahlılar kənd tam orta ümumtəhsil məktəbi',
      'Sarısu kənd ümumi orta məktəbi',
      'Şəhriyar kənd tam orta ümumtəhsil məktəbi',
      'Yenikənd kənd tam orta ümumtəhsil məktəbi',
      'Zurnabad kənd tam orta ümumtəhsil məktəbi',
    ],
  },
  {
    label: 'Daşkəsən rayonu',
    schools: [
      'Daşkəsən şəhər S.Vurğun adına 1 nömrəli tam orta ümumtəhsil məktəbi',
      'Daşkəsən şəhər A.Mürsəlov adına 2 nömrəli tam orta ümumtəhsil məktəbi',
      'Quşçu kənd tam orta ümumtəhsil məktəbi',
      'Bayan kənd tam orta ümumtəhsil məktəbi',
      'Əhmədli kənd tam orta ümumtəhsil məktəbi',
      'Alaxançallı kənd tam orta ümumtəhsil məktəbi',
      'Zivlan kənd tam orta ümumtəhsil məktəbi',
      'Gurbulaq kənd tam orta ümumtəhsil məktəbi',
      'Xoşbulaq kənd tam orta ümumtəhsil məktəbi',
      'Almalı kənd ümumi orta məktəbi',
      'Astaf kənd tam orta ümumtəhsil məktəbi',
      'Çaykənd kənd tam orta ümumtəhsil məktəbi',
      'Çıraqlı kənd tam orta ümumtəhsil məktəbi',
      'Daşkəsən kənd tam orta ümumtəhsil məktəbi',
      'Emilli kənd tam orta ümumtəhsil məktəbi',
      'Göyvilyurd kənd tam orta ümumtəhsil məktəbi',
      'Xaçbulaq kənd tam orta ümumtəhsil məktəbi',
      'Qabaqtəpə kənd tam orta ümumtəhsil məktəbi',
      'Qarataq kənd ümumi orta məktəbi',
      'Mollahasanlı kənd tam orta ümumtəhsil məktəbi',
      'Muganlı kənd tam orta ümumtəhsil məktəbi',
      'Pirverdilər kənd tam orta ümumtəhsil məktəbi',
      'Quşçu qəsəbə tam orta ümumtəhsil məktəbi',
      'Səbətkeçməz kənd tam orta ümumtəhsil məktəbi',
      'Şahvələdli kənd tam orta ümumtəhsil məktəbi',
      'Tazakənd kənd tam orta ümumtəhsil məktəbi',
      'Yenikənd kənd tam orta ümumtəhsil məktəbi',
      'Yolqullar kənd tam orta ümumtəhsil məktəbi',
      'Daşkəsən rayon Çanaqçı kənd tam orta ümumtəhsil məktəbi',
      'Daşkəsən şəhər N.Nərimanov adına 3 nömrəli tam orta ümumtəhsil məktəbi',
      'E.Məmmədov adına Goranlı kənd tam orta ümumtəhsil məktəbi',
      'Daşkəsən şəhəri İmadəddin Nəsimi adına 1 nömrəli tam orta ümumtəhsil məktəbi',
    ],
  },
  {
    label: 'Goranboy rayonu',
    schools: [
      'Goranboy şəhər 1 nömrəli tam orta ümumtəhsil məktəbi',
      'Goranboy şəhər 2 nömrəli tam orta ümumtəhsil məktəbi',
      'Dəliməmmədli şəhər tam orta ümumtəhsil məktəbi',
      'Aşağı Ağcakənd qəsəbə tam orta ümumtəhsil məktəbi',
      'Qazanbulaq qəsəbə tam orta ümumtəhsil məktəbi',
      'Goran qəsəbə tam orta ümumtəhsil məktəbi',
      'Xan Qərvənd kənd tam orta ümumtəhsil məktəbi',
      'Səfikürd kənd tam orta ümumtəhsil məktəbi',
      'Tap Qaraqoyunlu kənd tam orta ümumtəhsil məktəbi',
      'Borsunlu kənd tam orta ümumtəhsil məktəbi',
      'Qızılhacılı kənd 1 nömrəli tam orta ümumtəhsil məktəbi',
      'Qızılhacılı kənd 2 nömrəli tam orta ümumtəhsil məktəbi',
      'Boluslu kənd tam orta ümumtəhsil məktəbi',
      'Nadir kənd tam orta ümumtəhsil məktəbi',
      'Veyisli kənd tam orta ümumtəhsil məktəbi',
      'Alpout kənd tam orta ümumtəhsil məktəbi',
      'Baxçakürd kənd tam orta ümumtəhsil məktəbi',
      'Abram kənd tam orta ümumtəhsil məktəbi',
      'Buzluq kənd ümumi orta məktəbi',
      'Gülüstan kənd tam orta ümumtəhsil məktəbi',
      'Ərzuman kənd tam orta ümumtəhsil məktəbi',
      'Fəxralı kənd tam orta ümumtəhsil məktəbi',
      'Qaradağlı kənd tam orta ümumtəhsil məktəbi',
      'Qaraməmmədli kənd tam orta ümumtəhsil məktəbi',
      'Qazan kənd tam orta ümumtəhsil məktəbi',
      'Quşçular kənd tam orta ümumtəhsil məktəbi',
      'Meşəli kənd ümumi orta məktəbi',
      'Sarısu kənd tam orta ümumtəhsil məktəbi',
      'Semax kənd ümumi orta məktəbi',
      'Toly kənd tam orta ümumtəhsil məktəbi',
      'Xoylunlu kənd tam orta ümumtəhsil məktəbi',
      'Zeyva kənd tam orta ümumtəhsil məktəbi',
      'Goranboy rayon İnteqrasiya təlimli İnternat Tipli Gimnaziya',
      'Goranboy rayon Qarasuçu kənd tam orta ümumtəhsil məktəbi',
      'Goranboy rayon Çingiz Hümbətov adına Yeniyol kənd tam orta ümumtəhsil məktəbi',
      'Goranboy rayon Miraləm Həsənov adına Əlirzalı kənd tam orta ümumtəhsil məktəbi',
      'Daşkəsən rayonu Kəmərqaya kənd Fərhad Ələsgərov adına tam orta ümumtəhsil məktəbi',
      'Hafiz Qasımov adına Əmirvar kənd tam orta ümumtəhsil məktəbi',
      'Goranboy rayon Niyazi Aslanov adına Tapqaraqoyunlu kənd tam orta ümumtəhsil məktəbi',
    ],
  },
  {
    label: 'Samux rayonu',
    schools: [
      'Samux şəhər 1 nömrəli tam orta ümumtəhsil məktəbi',
      'Samux şəhər 2 nömrəli tam orta ümumtəhsil məktəbi',
      'Samux rayon Alıuşağı kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Burunqovaq kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Çobanddağ kənd ümumi orta məktəbi',
      'Samux rayon Əhmədbəyli kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Əli Bayramlı kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Füzuli kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Göyüşlü kənd ümumi orta məktəbi',
      'Samux rayon Hacıalılı kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon İnstitut qəsəbə tam orta ümumtəhsil məktəbi',
      'Samux rayon Kəsəmən kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Kolayır kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Qarabağlar kənd 1 nömrəli tam orta ümumtəhsil məktəbi',
      'Samux rayon Qarabağlar kənd 2 nömrəli tam orta ümumtəhsil məktəbi',
      'Samux rayon Qarabağlı kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Qədili kənd ümumi orta məktəbi',
      'Samux rayon Qırıqlı kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Qobustu kənd əsas məktəbi',
      'Samux rayon Ləki kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Poylu kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Poylu qəsəbə tam orta ümumtəhsil məktəbi',
      'Samux rayon Salahlı kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Səfərliyev adına qəsəbə tam orta ümumtəhsil məktəbi',
      'Samux rayon Sərkar kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Seyidlər kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Tatlı kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Yenikənd kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Yenidövran qəsəbə tam orta ümumtəhsil məktəbi',
      'Samux rayon Ziyadlı kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon İstixana qəsəbə ümumi orta məktəbi',
      'Samux rayon Ləki kənd ümumi orta məktəbi',
      'Samux rayon Poylu kənd ümumi orta məktəbi',
      'Samux rayon Qəsəbə tam orta ümumtəhsil məktəbi',
      'Samux rayon Kolayır kənd əsas məktəbi',
      'Samux rayon İmadəddin Nəsimi adına Ziyadlı kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon H.Məmmədov adına Qaraağaclı qəsəbə tam orta ümumtəhsil məktəbi',
      'Samux rayon Qarayeri qəsəbə 1 nömrəli məktəb lisey',
      'Samux rayon Yuxarı Ağasıbəyli kənd tam orta ümumtəhsil məktəbi',
      'Samux rayon Seyidlər kənd 1 nömrəli tam orta ümumtəhsil məktəbi',
    ],
  },
  {
    label: 'Naftalan şəhəri',
    schools: [
      'Naftalan şəhər İ.Nəsimi adına 1 nömrəli tam orta ümumtəhsil məktəbi',
      'Naftalan şəhər Z.Rüstəmov adına 2 nömrəli tam orta ümumtəhsil məktəbi',
      'Naftalan şəhər Qaşaltı Qaraqoyunlu kənd tam orta ümumtəhsil məktəbi',
    ],
  },
];
